# Generated by Django 2.0.7 on 2020-05-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(choices=[('WHITE', 'white'), ('BLUE', 'blue'), ('BLACK', 'black'), ('GREEN', 'green')], max_length=10)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
