# Generated by Django 2.0.7 on 2020-05-24 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybokeh', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='myProducts',
            new_name='myProduct',
        ),
    ]
