# Generated by Django 2.0.7 on 2020-06-10 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybokeh', '0002_auto_20200524_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='mycolors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colorname', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'colors',
            },
        ),
    ]
