# Generated by Django 2.0.7 on 2020-06-30 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybokeh', '0005_auto_20200611_2002'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mysymbols_cl',
        ),
    ]
